---
title: "Additional Manuscript Figures"
output:
  rmarkdown::html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: paged
  rmarkdown::html_vignette: default
# runtime: shiny
vignette: >
  %\VignetteIndexEntry{Additional Manuscript Figures}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::knitr}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache.path="./"
)
```


```{r message=FALSE, warning=FALSE}
rm(list = ls())
library(dplyr)
library(ggplot2)
library(ggthemes)
library(forcats)
library(tidyr)
library(reshape2)
library(bnlearn)
library(bnaiaR)
library(kableExtra)

PLOTWIDTH = 16
PLOTHEIGHT = 9
SAVEPLOTS <- FALSE
PLOTPATH <- Sys.getenv("PLOTPATH")
```

# Load Preprocessed Data

```{r load_data}
data("adbisgc")
str(adbisgc, give.attr=F)
# summarytools::dfSummary(adbisgc)
```

```{r}
adbisgc_reg <- adbisgc %>%
  mutate(gender = fct_relevel(gender,c("male","female"))) %>%
  # mutate(age_diag_group = fct_relevel(age_diag_group, c(LETTERS[seq(8,1,-1)]))) %>% # keep them alphabetically.
  mutate(positive_famillial_history = fct_relevel(positive_famillial_history, c("no", "probably", "yes"))) %>%
  mutate(smoking_current_former_no = fct_relevel(smoking_current_former_no, c("no","former","current"))) %>%
  mutate(smoking_current_notcurrent = fct_relevel(smoking_current_notcurrent, c("not_current", "current"))) %>%
  mutate(multipleIAs = fct_relevel(multipleIAs, c("no", "yes"))) %>%
  mutate(hpt_aware = fct_relevel(hpt_aware,c("no","yes"))) %>%
  mutate(IAlocation_group = fct_relevel(IAlocation_group, c("low","medium","high")))%>%
  mutate(IAruptured = fct_relevel(IAruptured,c("no","yes"))) 
  # mutate(IAsize_diag_grouped_merged = fct_relevel(IAsize_diag_grouped_merged, c(LETTERS[seq(3,1,-1)])))
str(adbisgc_reg, give.attr=F)
# summarytools::dfSummary(adbisgc_reg)
```


```{r}
plt_overv_adbisgc <- overview_plt_max_grouped(adbisgc_reg, cont.vars=c("age_diag", "IAsize_diag", "IAsize_diag_log", "number_of_IAs", "maxFUtime"), disc.cont.ratio=c(5,2))

if (SAVEPLOTS) {
  ggsave(
    plot = plt_overv_adbisgc,
    filename = "overviewplt_df_adbisgc.pdf",
    path = PLOTPATH,
    dpi = 600, width = PLOTWIDTH, height = PLOTHEIGHT*2
  )
} else {
  plt_overv_adbisgc
}
```


## Select bnaiaR variables


```{r}
bnaiar_vars <- c("ID_1", 
           "study_source", 
           "gender", 
           "age_diag", "age_diag_group", 
           "positive_famillial_history", 
           "hpt_aware", 
           "smoking_current_notcurrent", 
           "multipleIAs", 
           "IAlocation", "IAlocation_group", 
           "IAsize_diag", "IAsize_diag_log", "IAsize_diag_grouped", "IAsize_diag_grouped_merged",
           "IAruptured")

df_bnaiar <- adbisgc_reg %>%
  select(all_of(bnaiar_vars))
```

```{r}
# summarytools::dfSummary(df_bnaiar)
# summarytools::view(dfSummary(df_bnaiar), method = "pander", file = "~/ZHAW/ExplorDataISGC/220623_HUG-ZHAW_Retreat/summary_adbisgc_bnaiaR.html")
str(df_bnaiar, give.attr=F)
```

```{r}
plt_overv_bnaiar <- overview_plt_max_grouped(df_bnaiar)

if (SAVEPLOTS) {
  ggsave(
    plot = plt_overv_bnaiar,
    filename = "overviewplt_df_bnaiar.pdf",
    path = PLOTPATH,
    dpi = 600, width = PLOTWIDTH, height = PLOTHEIGHT*1.5
  )
} else {
  plt_overv_bnaiar
}
```



## bnaiaR vars with only complete entries

```{r}
df_bnaiar_compl <- df_bnaiar %>%
  na.omit() 

summarytools::dfSummary(df_bnaiar_compl)
```

```{r}
plt_overv_bnaiar_compl <- overview_plt_max_grouped(df_bnaiar_compl)

if (SAVEPLOTS) {
  ggsave(
    plot = plt_overv_bnaiar_compl,
    filename = "overviewplt_df_bnaiar_compl.pdf",
    path = PLOTPATH,
    dpi = 600, width = PLOTWIDTH, height = PLOTHEIGHT*1.5
  )
} else {
  plt_overv_bnaiar_compl
}
```

```{r}
cont.vars=c("age_diag", "IAsize_diag", "IAsize_diag_log")

df_counts <- data.frame(matrix(ncol=6, nrow = 0))
colnames(df_counts) <- c("study", "variable", "level", "count", "total", "prop")

i <- 1
for (study in unique(df_bnaiar_compl$study_source)){
  print(study)
  df_temp <- df_bnaiar_compl %>%
  select(-c(cont.vars, "ID_1")) %>%
  filter(study_source == study)
  
  tot <- nrow(df_temp)
  for (var in colnames(df_temp)){
    for(lev in levels(df_temp[[var]])){
    cnt <- length(df_temp[[var]][which(df_temp[[var]] == lev)])
    
    df_counts[i,] <- c(study, var, lev, cnt, tot, NA)
    i <- i+1
    }
  }
}

radar_age <- df_counts %>%
  mutate(prop = as.integer(count)/as.integer(total)) %>%
  mutate(across(c("count", "total"), as.integer)) %>% 
  filter(variable == "age_diag_group") %>%
  pivot_wider(id_cols = c("study"), names_from = c("level"), values_from = prop) %>%
  
  ggradar::ggradar(plot.title = "age_diag_group",
                   group.point.size = 3, plot.legend = FALSE)

radar_pfh <- df_counts %>%
  mutate(prop = as.integer(count)/as.integer(total)) %>%
  mutate(across(c("count", "total"), as.integer)) %>% 
  filter(variable == "positive_famillial_history") %>%
  pivot_wider(id_cols = c("study"), names_from = c("level"), values_from = prop) %>%
  
  ggradar::ggradar(plot.title = "positive_famillial_history",
                   group.point.size = 3, plot.legend = FALSE)

radar_hpt <- df_counts %>%
  mutate(prop = as.integer(count)/as.integer(total)) %>%
  mutate(across(c("count", "total"), as.integer)) %>% 
  filter(variable == "hpt_aware") %>%
  pivot_wider(id_cols = c("study"), names_from = c("level"), values_from = prop) %>%
  
  ggradar::ggradar(plot.title = "hpt_aware",
                   group.point.size = 3, plot.legend = FALSE)

radar_smoke <- df_counts %>%
  mutate(prop = as.integer(count)/as.integer(total)) %>%
  mutate(across(c("count", "total"), as.integer)) %>% 
  filter(variable == "smoking_current_notcurrent") %>%
  pivot_wider(id_cols = c("study"), names_from = c("level"), values_from = prop) %>%
  
  ggradar::ggradar(plot.title = "smoking_current_notcurrent",
                   group.point.size = 3, plot.legend = FALSE)

radar_mult <- df_counts %>%
  mutate(prop = as.integer(count)/as.integer(total)) %>%
  mutate(across(c("count", "total"), as.integer)) %>% 
  filter(variable == "multipleIAs") %>%
  pivot_wider(id_cols = c("study"), names_from = c("level"), values_from = prop) %>%
  
  ggradar::ggradar(plot.title = "multipleIAs",
                   group.point.size = 3, plot.legend = FALSE)

radar_loc <- df_counts %>%
  mutate(prop = as.integer(count)/as.integer(total)) %>%
  mutate(across(c("count", "total"), as.integer)) %>% 
  filter(variable == "IAlocation_group") %>%
  pivot_wider(id_cols = c("study"), names_from = c("level"), values_from = prop) %>%
  
  ggradar::ggradar(plot.title = "IAlocation_group",
                   group.point.size = 3, plot.legend = FALSE)

radar_size <- df_counts %>%
  mutate(prop = as.integer(count)/as.integer(total)) %>%
  mutate(across(c("count", "total"), as.integer)) %>% 
  filter(variable == "IAsize_diag_grouped_merged") %>%
  pivot_wider(id_cols = c("study"), names_from = c("level"), values_from = prop) %>%
  
  ggradar::ggradar(plot.title = "IAsize_diag_grouped_merged",
                   group.point.size = 3, plot.legend = FALSE)

radar_rupt <- df_counts %>%
  mutate(prop = as.integer(count)/as.integer(total)) %>%
  mutate(across(c("count", "total"), as.integer)) %>% 
  filter(variable == "IAruptured") %>%
  pivot_wider(id_cols = c("study"), names_from = c("level"), values_from = prop) %>%
  
  ggradar::ggradar(plot.title = "IAruptured",
                   group.point.size = 3, legend.position = "right")

plt_overv_bnaiar_compl_radar <- patchwork::wrap_plots(radar_age, radar_pfh, radar_hpt, radar_smoke, radar_mult, radar_loc, radar_size, radar_rupt,
                                                      ncol=3, widths = c(3,3))

if (SAVEPLOTS) {
  ggsave(
    plot = plt_overv_bnaiar_compl_radar,
    filename = "overviewplt_df_bnaiar_compl_radar.pdf",
    path = PLOTPATH,
    dpi = 600, width = PLOTWIDTH*1.2, height = PLOTHEIGHT
  )
} else {
  plt_overv_bnaiar_compl_radar
}
```

```{r}
paint <- c('#b4d2b1', '#568f8b', '#1d4a60', '#cd7e59', '#ddb247', '#d15252')

df_counts %>%
  mutate(prop = as.integer(count)/as.integer(total)) %>%
  mutate(across(c("count", "total"), as.integer)) %>% 
  filter(variable == "age_diag_group") %>%
  # pivot_wider(id_cols = c("study"), names_from = c("level"), values_from = prop) %>%
  
  ggplot(., aes(x = level, y= prop, fill = study)) +
  # geom_histogram(stat = "count", position = "dodge") +
  geom_col() +
  theme_minimal() +
  scale_fill_manual(values = paint) +
  # ggtitle(deparse(substitute(df))) +
  theme(
    legend.spacing = unit(1, "cm"),
    # axis.text.x = element_blank(),
    axis.text.x = element_text(
      angle = 45,
      vjust = 1,
      hjust = 1,
      margin = margin(10, 10, 10, 10)
    ),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  )
```
one color adds up to 1


```{r}
plt_overv_bnaiar_compl_rupture <- overview_plt_max_grouped_rupture(df_bnaiar_compl, colorby = "IAruptured")

if (SAVEPLOTS) {
  ggsave(
    plot = plt_overv_bnaiar_compl_rupture,
    filename = "overviewplt_df_bnaiar_compl_rupture.pdf",
    path = PLOTPATH,
    dpi = 600, width = PLOTWIDTH, height = PLOTHEIGHT*1.5
  )
} else {
  plt_overv_bnaiar_compl_rupture
}
```

table of variable level distribution
```{r}
var_level_dist <- df_bnaiar_compl %>%
  select(-c(cont.vars, "ID_1", "IAlocation", "IAsize_diag_grouped", "study_source")) %>% 
  filter(positive_famillial_history != "probably") %>%
  gather("key", "value") %>%
  group_by(key, value) %>%
  summarise(no_records = n(), .groups = "drop_last") %>%
  mutate(prop = round(no_records/sum(no_records), 3)) %>%
  mutate(percent = prop*100)

if (SAVEPLOTS) {
  write.csv(var_level_dist, file = paste0(PLOTPATH, "/var_level_dist.csv"))
} else {
  var_level_dist
}
```







# Overview Plots

```{r}
overview_plt_max(df_bnaiar_compl)
overview_plt_max(dfdbn)
```


# One plot for each variable

```{r sex}
pltSexdisc_raw <- dfdbn %>%
  select(Gender) %>%
  gather(cols, value) %>%
  
  ggplot() +
  aes(x = value) +
  geom_histogram(stat = "count")


pltSexdisc <- pltSexdisc_raw+
  ggtitle("Sex")+
  xlab(" ") +
  ylab("Number of records")+
  theme(axis.text.x.bottom = element_blank())+
  theme_tufte()
print(pltSexdisc)
```


```{r age}
pltAge_raw <- dfabn %>%
  select(AgeDiag) %>%
  gather(cols, value) %>%
  
  ggplot() +
  aes(x = value) +
  geom_histogram(stat = "count")


pltAge <- pltAge_raw+
  ggtitle("Age")+
  xlab("years") +
  ylab("Number of records")+
  theme_tufte()
print(pltAge)
```

```{r age disc}
maxage <- max(dfabn$AgeDiag)
pltAgedisc_raw <- dfdbn %>%
  select(AgeDiag.group) %>%
  gather(cols, value) %>%
  
  ggplot() +
  aes(x = value) +
  geom_histogram(stat = "count")


pltAgedisc <- pltAgedisc_raw+
  # scale_x_discrete(labels = c("A=[0,40)", "B=[40,45)", "C=[45,50)", "D=[50,55)", "E=[55,60)", "F=[60,65)", paste0("G=[65,", maxage, ")"))) +
  scale_x_discrete(labels = c("[0,40)", "[40,45)", "[45,50)", "[50,55)", "[55,60)", "[60,65)", paste0("[65,", maxage, ")"))) +
  ggtitle("Age")+
  xlab("age groups") +
  ylab("Number of records")+
  theme_tufte()
print(pltAgedisc)
```

```{r age overlay}
df.age <- adbisgc_reg %>% 
  filter(age_diag != 0) %>%
  select(c(age_diag, age_diag_group)) %>%
  arrange(age_diag)

df.age.cont <- adbisgc_reg %>% 
  filter(age_diag != 0) %>%
  select(c(age_diag, age_diag_group)) %>%
  arrange(age_diag) %>%
  count(age_diag, name="AgeDiag.n")

df.age.group <- adbisgc_reg %>% 
  filter(age_diag != 0) %>%
  select(c(age_diag, age_diag_group)) %>%
  arrange(age_diag) %>%
  count(age_diag_group,  name="AgeDiag.group.n")

plt.overlay.age <- df.age.cont %>%
  ggplot() +
  annotate(
    "rect",
    xmin = c(
      min(df.age$age_diag[which(df.age$age_diag_group == "A")]),
      min(df.age$age_diag[which(df.age$age_diag_group == "B")]),
      min(df.age$age_diag[which(df.age$age_diag_group == "C")]),
      min(df.age$age_diag[which(df.age$age_diag_group == "D")]),
      min(df.age$age_diag[which(df.age$age_diag_group == "E")]),
      min(df.age$age_diag[which(df.age$age_diag_group == "F")]),
      min(df.age$age_diag[which(df.age$age_diag_group == "G")])
    ),
    xmax = c(
      max(df.age$age_diag[which(df.age$age_diag_group == "A")]),
      max(df.age$age_diag[which(df.age$age_diag_group == "B")]),
      max(df.age$age_diag[which(df.age$age_diag_group == "C")]),
      max(df.age$age_diag[which(df.age$age_diag_group == "D")]),
      max(df.age$age_diag[which(df.age$age_diag_group == "E")]),
      max(df.age$age_diag[which(df.age$age_diag_group == "F")]),
      max(df.age$age_diag[which(df.age$age_diag_group == "G")])
    ),
    ymin = rep(0, 7),
    ymax = df.age.group$AgeDiag.group.n,
    alpha = 0.2,
    color = "gray",
    fill = "lightgray"
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, .2)))+
  geom_text(label = "A", family = "serif",
            x=min(df.age$age_diag[which(df.age$age_diag_group == "A")])+((max(df.age$age_diag[which(df.age$age_diag_group == "A")])-min(df.age$age_diag[which(df.age$age_diag_group == "A")]))/2), 
            y=df.age.group$AgeDiag.group.n[1]*1.1)+
  geom_text(label = "B",  family = "serif",
            x=min(df.age$age_diag[which(df.age$age_diag_group == "B")])+((max(df.age$age_diag[which(df.age$age_diag_group == "B")])-min(df.age$age_diag[which(df.age$age_diag_group == "B")]))/2), 
            y=df.age.group$AgeDiag.group.n[2]*1.1)+
  geom_text(label = "C",  family = "serif",
            x=min(df.age$age_diag[which(df.age$age_diag_group == "C")])+((max(df.age$age_diag[which(df.age$age_diag_group == "C")])-min(df.age$age_diag[which(df.age$age_diag_group == "C")]))/2), 
            y=df.age.group$AgeDiag.group.n[3]*1.1)+
  geom_text(label = "D",  family = "serif",
            x=min(df.age$age_diag[which(df.age$age_diag_group == "D")])+((max(df.age$age_diag[which(df.age$age_diag_group == "D")])-min(df.age$age_diag[which(df.age$age_diag_group == "D")]))/2), 
            y=df.age.group$AgeDiag.group.n[4]*1.1)+
  geom_text(label = "E",  family = "serif",
            x=min(df.age$age_diag[which(df.age$age_diag_group == "E")])+((max(df.age$age_diag[which(df.age$age_diag_group == "E")])-min(df.age$age_diag[which(df.age$age_diag_group == "E")]))/2), 
            y=df.age.group$AgeDiag.group.n[5]*1.1)+
  geom_text(label = "F",  family = "serif",
            x=min(df.age$age_diag[which(df.age$age_diag_group == "F")])+((max(df.age$age_diag[which(df.age$age_diag_group == "F")])-min(df.age$age_diag[which(df.age$age_diag_group == "F")]))/2), 
            y=df.age.group$AgeDiag.group.n[6]*1.1)+
  geom_text(label = "G",  family = "serif",
            x=min(df.age$age_diag[which(df.age$age_diag_group == "G")])+((max(df.age$age_diag[which(df.age$age_diag_group == "G")])-min(df.age$age_diag[which(df.age$age_diag_group == "G")]))/2), 
            y=df.age.group$AgeDiag.group.n[7]*1.05)+
  # Age group cont
  geom_col(aes(x = age_diag, y = AgeDiag.n), width = 0.5) +
  # Layouting
  theme_tufte()+
  scale_x_continuous(breaks = c(min(df.age.cont$age_diag), 40, seq(40, 65, 5), max(df.age.cont$age_diag)),
                     minor_breaks = seq(45, 65, 5)) +
  labs(
    title = "Age",
    y = "Number of records",
    x = "years"
  ) +
  theme(
    plot.caption = element_text(hjust = 0.5),
    plot.caption.position = "plot",
    panel.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", colour = NA)
  )



plt.overlay.age.large <- df.age.cont %>%
  ggplot() +
  
  # Age group fine
  annotate(
    "rect",
    xmin = c(
      min(df.age$age_diag[which(df.age$age_diag_group == "A")]),
      min(df.age$age_diag[which(df.age$age_diag_group == "B")]),
      min(df.age$age_diag[which(df.age$age_diag_group == "C")]),
      min(df.age$age_diag[which(df.age$age_diag_group == "D")]),
      min(df.age$age_diag[which(df.age$age_diag_group == "E")]),
      min(df.age$age_diag[which(df.age$age_diag_group == "F")]),
      min(df.age$age_diag[which(df.age$age_diag_group == "G")])
    ),
    xmax = c(
      max(df.age$age_diag[which(df.age$age_diag_group == "A")]),
      max(df.age$age_diag[which(df.age$age_diag_group == "B")]),
      max(df.age$age_diag[which(df.age$age_diag_group == "C")]),
      max(df.age$age_diag[which(df.age$age_diag_group == "D")]),
      max(df.age$age_diag[which(df.age$age_diag_group == "E")]),
      max(df.age$age_diag[which(df.age$age_diag_group == "F")]),
      max(df.age$age_diag[which(df.age$age_diag_group == "G")])
    ),
    ymin = rep(0, 7),
    ymax = df.age.group$AgeDiag.group.n,
    alpha = 0.2,
    color = "gray",
    fill = "lightgray"
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, .2)))+
  geom_text(label = "A", family = "serif", size=8,
            x=min(df.age$age_diag[which(df.age$age_diag_group == "A")])+((max(df.age$age_diag[which(df.age$age_diag_group == "A")])-min(df.age$age_diag[which(df.age$age_diag_group == "A")]))/2), 
            y=df.age.group$AgeDiag.group.n[1]*1.1)+
  geom_text(label = "B",  family = "serif", size=8,
            x=min(df.age$age_diag[which(df.age$age_diag_group == "B")])+((max(df.age$age_diag[which(df.age$age_diag_group == "B")])-min(df.age$age_diag[which(df.age$age_diag_group == "B")]))/2), 
            y=df.age.group$AgeDiag.group.n[2]*1.1)+
  geom_text(label = "C",  family = "serif", size=8,
            x=min(df.age$AgeDiag[which(df.age$age_diag_group == "C")])+((max(df.age$AgeDiag[which(df.age$age_diag_group == "C")])-min(df.age$AgeDiag[which(df.age$age_diag_group == "C")]))/2), 
            y=df.age.group$AgeDiag.group.n[3]*1.1)+
  geom_text(label = "D",  family = "serif", size=8,
            x=min(df.age$age_diag[which(df.age$age_diag_group == "D")])+((max(df.age$age_diag[which(df.age$age_diag_group == "D")])-min(df.age$age_diag[which(df.age$age_diag_group == "D")]))/2), 
            y=df.age.group$AgeDiag.group.n[4]*1.1)+
  geom_text(label = "E",  family = "serif", size=8,
            x=min(df.age$age_diag[which(df.age$age_diag_group == "E")])+((max(df.age$age_diag[which(df.age$age_diag_group == "E")])-min(df.age$age_diag[which(df.age$age_diag_group == "E")]))/2), 
            y=df.age.group$AgeDiag.group.n[5]*1.1)+
  geom_text(label = "F",  family = "serif", size=8,
            x=min(df.age$age_diag[which(df.age$age_diag_group == "F")])+((max(df.age$age_diag[which(df.age$age_diag_group == "F")])-min(df.age$age_diag[which(df.age$age_diag_group == "F")]))/2), 
            y=df.age.group$AgeDiag.group.n[6]*1.1)+
  geom_text(label = "G",  family = "serif", size=8,
            x=min(df.age$age_diag[which(df.age$age_diag_group == "G")])+((max(df.age$age_diag[which(df.age$age_diag_group == "G")])-min(df.age$age_diag[which(df.age$age_diag_group == "G")]))/2), 
            y=df.age.group$AgeDiag.group.n[7]*1.05)+
  # Age group cont
  geom_col(aes(x = age_diag, y = AgeDiag.n), width = 0.5) +
  # Layouting
  theme_tufte()+
  scale_x_continuous(breaks = c(min(df.age.cont$age_diag), 40, seq(40, 65, 5), max(df.age.cont$age_diag)),
                     minor_breaks = seq(45, 65, 5)) +
  labs(
    title = "Age",
    y = "Number of records",
    x = "years"
  ) +
  theme(
    plot.caption = element_text(hjust = 0.5),
    plot.caption.position = "plot",
    panel.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", colour = NA),
    
    title = element_text(size = 32),
          text = element_text(size = 30),
          axis.text = element_text(size = 30),
          axis.title = element_text(size = 30),
          legend.text = element_text(size = 30),
          legend.title = element_text(size = 32))
plt.overlay.age.large
  
if (SAVEPLOTS) {
  ggsave(
    plot = plt.overlay.age,
    filename = "age_overlay.pdf",
    path = PLOTPATH,
    dpi = 600
  )
} else {
  plt.overlay.age
}
```

```{r Fam. History}
pltfam_raw <- dfdbn %>%
  select(Positive.famillial.history) %>%
  gather(cols, value) %>%
  
  ggplot() +
  aes(x = value) +
  geom_histogram(stat = "count")


pltfam <- pltfam_raw+
  ggtitle("Fam. History")+
  xlab(" ") +
  ylab("Number of records")+
  theme(axis.text.x.bottom = element_blank())+
  theme_tufte()
print(pltfam)
```

```{r Hypertension}
pltHBP_raw <- dfdbn %>%
  select(Hypertension) %>%
  gather(cols, value) %>%
  
  ggplot() +
  aes(x = value) +
  geom_histogram(stat = "count")


pltHBP <- pltHBP_raw+
  scale_x_discrete(labels = c("Any Type", "Never")) +
  ggtitle("Hypertension")+
  xlab(" ") +
  ylab("Number of records")+
  theme(axis.text.x.bottom = element_blank())+
  theme_tufte()
print(pltHBP)
```

```{r Smoking}
pltSmoke_raw <- dfdbn %>%
  select(Smoking_Current_Former_No) %>%
  gather(cols, value) %>%
  
  ggplot() +
  aes(x = value) +
  geom_histogram(stat = "count")


pltSmoke <- pltSmoke_raw+
  # scale_x_discrete(labels = c("Any Type", "Never")) +
  ggtitle("Smoking")+
  xlab(" ") +
  ylab("Number of records")+
  theme(axis.text.x.bottom = element_blank())+
  theme_tufte()
print(pltSmoke)
```

```{r Multiple}
pltMulti_raw <- dfdbn %>%
  select(Multiple.IAs) %>%
  gather(cols, value) %>%
  
  ggplot() +
  aes(x = value)  +
  geom_histogram(stat = "count")


pltMulti <- pltMulti_raw+
  ggtitle("Multiple IA")+
  xlab(" ") +
  ylab("Number of records")+
  theme(axis.text.x.bottom = element_blank())+
  theme_tufte()
print(pltMulti)
```

```{r Location}
pltloc_raw <- dfdbn %>%
  select(location.grouped) %>%
  gather(cols, value) %>%
  
  ggplot() +
  aes(x = value)  +
  geom_histogram(stat = "count")


pltloc <- pltloc_raw+
  ggtitle("Location")+
  xlab(" ") +
  ylab("Number of records")+
  theme(axis.text.x.bottom = element_blank())+
  theme_tufte()
print(pltloc)
```

```{r}
df.loc <- adbisgc_reg %>%
  select(c(IAlocation, IAlocation_group)) %>%
  filter(!is.na(IAlocation) & IAlocation != "Infundibulum") %>%
  # mutate(IAlocation = factor(IAlocation, levels = c("NA", "Infundibulum", 
  #                                                   "A1 segment ant", "Other", "Basilar", "ICA", "MCA", 
  #                                                   "PC", "A2", "V-B", "Pcom", "Acom", 
  #                                                   "CavICA", "OphtICA")))
    mutate(IAlocation = factor(IAlocation, levels = c("PC", "A2", "V-B", "Pcom", "Acom", 
                                                      "A1 segment ant", "Other", "Basilar", "ICA", "MCA", 
                                                      "CavICA", "OphtICA")))
str(df.loc)

plt.loc.comb <- df.loc %>%
  # Plot
  ggplot()+
  aes(x=IAlocation, fill=IAlocation_group)+
  geom_bar() +
  theme_minimal()+
  labs(title= "IA location",
       y="Number of records",
       x=NULL)+
  # scale_fill_manual(values=c("Low"="darkgreen", "Medium"= "darkorange", "High" = "darkred"), name = "Risk of IA rupture")+
  scale_fill_manual(values=c("low"=colorblind_pal()(8)[4], "medium"= colorblind_pal()(8)[2], "high" = colorblind_pal()(8)[7]), name = "Risk of IA rupture")+
  # scale_fill_tableau(name = "Risk of IA rupture")+
  theme_tufte()+
  theme(plot.caption = element_text(hjust = 0.5),
        plot.caption.position = "plot",
        legend.position = c(0.875,0.575))+
  coord_flip()

plt.loc.comb.large <- plt.loc.comb +
  theme(title = element_text(size = 32),
          text = element_text(size = 30),
          axis.text = element_text(size = 30),
          axis.title = element_text(size = 30),
          legend.text = element_text(size = 30),
          legend.title = element_text(size = 32),
        legend.position = c(0.75,0.575))
  
print(plt.loc.comb)
```

```{r IA size}
pltSize_raw <- dfabn %>%
  select(IAsize_log) %>%
  gather(cols, value) %>%
  
  ggplot() +
  aes(x = value)  +
  geom_bar(stat = "count", show.legend = TRUE, col="black", fill="gray") 


pltSize <- pltSize_raw+
  ggtitle("IA size")+
  xlab("log(IA size)") +
  ylab("Number of records")+
  theme(axis.text.x.bottom = element_blank())+
  theme_tufte()
print(pltSize)
```

```{r IA size discrete}
pltSizedisc_raw <- dfdbn %>%
  select(IAsize.groups.merged) %>%
  gather(cols, value) %>%
  
  ggplot() +
  aes(x = value)  +
  geom_histogram(stat = "count")


pltSizedisc <- pltSizedisc_raw+
  scale_x_discrete(labels = c("A≤7", "B=7-12", "C≥13")) +
  ggtitle("IA size")+
  xlab("[mm]") +
  ylab("Number of records")+
  theme(axis.text.x.bottom = element_blank())+
  theme_tufte()
print(pltSizedisc)
```

```{r IA size overlay}
df.size <- adb %>% 
    # Remove IA size outliers
  filter(IAsize_log < 4) %>%
  select(c(IAsize_log, IAsize.groups.merged)) %>%
  arrange(IAsize_log)

df.size.cont <- adb %>% 
    # Remove IA size outliers
  filter(IAsize_log < 4) %>%
  select(c(IAsize_log, IAsize.groups.merged)) %>%
  arrange(IAsize_log) %>%
  count(IAsize_log, name="IAsize.n")

df.size.group <- adb %>% 
    # Remove IA size outliers
  filter(IAsize_log < 4) %>%
  select(c(IAsize_log, IAsize.groups.merged)) %>%
  arrange(IAsize_log) %>%
  count(IAsize.groups.merged, name="IAsize.group.n")


plt.overlay.size <- df.size.cont %>%
  ggplot() +

  # Size group fine
  annotate(
    "rect",
    xmin = c(
      min(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "A")]),
      min(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "B")]),
      min(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "C")])
      # min(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "D")]),
    ),
    xmax = c(
      max(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "A")]),
      max(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "B")]),
      max(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "C")])
    #   max(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "D")]),
    ),
    ymin = rep(0, 3),
    ymax = df.size.group$IAsize.group.n/10,
    alpha = 0.2,
    color = "gray",
    fill = "lightgray"
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, .2)))+
  geom_text(label = "A≤7mm", family = "serif", fontface = "plain",
            x=min(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "A")])+((max(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "A")])-min(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "A")]))/2), 
            y=df.size.group$IAsize.group.n[1]/10*1.05)+
  geom_text(label = "B=7-12mm",  family = "serif", fontface = "plain",
            x=min(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "B")])+((max(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "B")])-min(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "B")]))/2), 
            y=df.size.group$IAsize.group.n[2]/10*1.1)+
  geom_text(label = "C≥13mm",  family = "serif", fontface = "plain",
            x=min(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "C")])+((max(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "C")])-min(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "C")]))/2), 
            y=df.size.group$IAsize.group.n[3]/10*1.3)+
  # geom_text(label = "D",  family = "serif", fontface = "plain",
  #           x=min(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "D")])+((max(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "D")])-min(df.size$IAsize_log[which(df.size$IAsize.groups.merged == "D")]))/2), 
  #           y=df.size.group$IAsize.group.n[4]*1.1)+

  # Size group cont
  geom_col(aes(x = IAsize_log, y = IAsize.n), width = 0.005) +
  # Layouting
  theme_tufte()+
  scale_x_continuous(breaks = round(c(seq(0, 4, 0.5)), 2)) +
  labs(
    title = "IA size",
    y = "Number of records",
    x = "log(IA size)"
  ) +
  theme(
    plot.caption = element_text(hjust = 0.5),
    plot.caption.position = "plot",
    panel.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", colour = NA)
  )

if (SAVEPLOTS) {
  ggsave(
    plot = plt.overlay.size,
    filename = "IAsize_overlay.png",
    path = PLOTPATH,
    dpi = 600
  )
} else {
  plt.overlay.size
}
```

```{r IA size mm overlay}
df.size <- adbisgc_reg %>% 
    # Remove IA size outliers
  filter(IAsize_diag_log < 4) %>%
  select(c(IAsize_diag, IAsize_diag_grouped_merged)) %>%
  arrange(IAsize_diag)

df.size.cont <- adbisgc_reg %>% 
    # Remove IA size outliers
  filter(IAsize_diag_log < 4) %>%
  select(c(IAsize_diag, IAsize_diag_grouped_merged)) %>%
  arrange(IAsize_diag) %>%
  count(IAsize_diag, name="IAsize.n")

df.size.group <- adbisgc_reg %>% 
    # Remove IA size outliers
  filter(IAsize_diag_log < 4) %>%
  select(c(IAsize_diag, IAsize_diag_grouped_merged)) %>%
  arrange(IAsize_diag) %>%
  count(IAsize_diag_grouped_merged, name="IAsize.group.n")

# small geom_text size
plt.overlay.size.mm <- df.size.cont %>%
  ggplot() +

  # Size group fine
  annotate(
    "rect",
    xmin = c(
      min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "A")]),
      min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "B")]),
      min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "C")])
      # min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "D")]),
    ),
    xmax = c(
      max(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "A")]),
      max(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "B")]),
      max(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "C")])
    #   max(df.size$IAsize_log[which(df.size$IAsize_diag_grouped_merged == "D")]),
    ),
    ymin = rep(0, 3),
    ymax = df.size.group$IAsize.group.n/10,
    alpha = 0.2,
    color = "gray",
    fill = "lightgray"
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, .2)))+
  geom_text(label = "A≤7mm", family = "serif", fontface = "plain",
            x=min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "A")])+((max(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "A")])-min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "A")]))/2),
            y=df.size.group$IAsize.group.n[1]/10*1.05)+
  geom_text(label = "B=7-12mm",  family = "serif", fontface = "plain",
            x=min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "B")])+((max(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "B")])-min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "B")]))/2),
            y=df.size.group$IAsize.group.n[2]/10*1.1)+
  geom_text(label = "C≥13mm",  family = "serif", fontface = "plain",
            x=min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "C")])+((max(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "C")])-min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "C")]))/2),
            y=df.size.group$IAsize.group.n[3]/10*1.3)+
  # geom_text(label = "D",  family = "serif", fontface = "plain",
  #           x=min(df.size$IAsize[which(df.size$IAsize_diag_grouped_merged == "D")])+((max(df.size$IAsize[which(df.size$IAsize_diag_grouped_merged == "D")])-min(df.size$IAsize[which(df.size$IAsize_diag_grouped_merged == "D")]))/2), 
  #           y=df.size.group$IAsize.group.n[4]*1.1)+

  # Size group cont
  geom_col(aes(x = IAsize_diag, y = IAsize.n), width=0.1, position = "dodge") +
  # Layouting
  theme_tufte()+
  # scale_x_continuous(breaks = round(c(seq(0, 4, 0.5)), 2)) +
  labs(
    title = "IA size",
    y = "Number of records",
    x = "[mm]"
  ) +
  theme(
    plot.caption = element_text(hjust = 0.5),
    plot.caption.position = "plot",
    panel.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", colour = NA)
  )

# large geom_text size
plt.overlay.size.mm.large <- df.size.cont %>%
  ggplot() +

  # Size group fine
  annotate(
    "rect",
    xmin = c(
      min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "A")]),
      min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "B")]),
      min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "C")])
      # min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "D")]),
    ),
    xmax = c(
      max(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "A")]),
      max(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "B")]),
      max(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "C")])
    #   max(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "D")]),
    ),
    ymin = rep(0, 3),
    ymax = df.size.group$IAsize.group.n/6,
    alpha = 0.2,
    color = "gray",
    fill = "lightgray"
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, .2)))+
  geom_text(label = "A", family = "serif", fontface = "plain", size = 8,
            x=min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "A")])+((max(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "A")])-min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "A")]))/2),
            y=df.size.group$IAsize.group.n[1]/6*1.05)+
  geom_text(label = "B",  family = "serif", fontface = "plain",size = 8,
            x=min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "B")])+((max(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "B")])-min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "B")]))/2),
            y=df.size.group$IAsize.group.n[2]/6*1.15)+
  geom_text(label = "C",  family = "serif", fontface = "plain", size = 8,
            x=min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "C")])+((max(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "C")])-min(df.size$IAsize_diag[which(df.size$IAsize_diag_grouped_merged == "C")]))/2),
            y=df.size.group$IAsize.group.n[3]/6*1.35)+
  # geom_text(label = "D",  family = "serif", fontface = "plain",
  #           x=min(df.size$IAsize[which(df.size$IAsize_diag_grouped_merged == "D")])+((max(df.size$IAsize[which(df.size$IAsize_diag_grouped_merged == "D")])-min(df.size$IAsize[which(df.size$IAsize_diag_grouped_merged == "D")]))/2), 
  #           y=df.size.group$IAsize.group.n[4]*1.1)+

  # Size group cont
  geom_col(aes(x = IAsize_diag, y = IAsize.n), width=0.1, position = "stack") +
  # Layouting
  theme_tufte()+
  # scale_x_continuous(breaks = round(c(seq(0, 4, 0.5)), 2)) +
  labs(
    title = "IA size",
    y = "Number of records",
    x = "[mm]"
  ) +
  theme(
    plot.caption = element_text(hjust = 0.5),
    plot.caption.position = "plot",
    panel.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", colour = NA),
    
    title = element_text(size = 30),
          text = element_text(size = 28),
          axis.text = element_text(size = 28),
          axis.title = element_text(size = 28),
          legend.text = element_text(size = 28),
          legend.title = element_text(size = 30))
plt.overlay.size.mm.large

if (SAVEPLOTS) {
  ggsave(
    plot = plt.overlay.size.mm.large,
    filename = "IAsize_overlay_mm.png",
    path = PLOTPATH,
    dpi = 600
  )
} else {
  plt.overlay.size.mm.large
}
```

```{r Ruptured IA}
pltRupt_raw <- dfdbn %>%
  select(Ruptured_IA) %>%
  gather(cols, value) %>%
  
  ggplot() +
  aes(x = value)  +
  geom_histogram(stat = "count")

pltRupt <- pltRupt_raw+
  ggtitle("Ruptured IA")+
  xlab(" ") +
  ylab("Number of records")+
  theme(axis.text.x.bottom = element_blank())+
  theme_tufte()
print(pltRupt)
```

# Combine to multiplot

```{r}
multplt <- plot_grid(plotlist = list(pltSexdisc, pltAge, pltAgedisc, pltfam,
                          pltHBP, pltSmoke,
                          pltMulti, pltloc, pltSize, pltSizedisc,
                          pltRupt)
          )

if (SAVEPLOTS) {
  ggsave(
    plot = multplt,
    filename = "vars_overview_multiplt.png",
    path = PLOTPATH,
    dpi = 600, width = PLOTWIDTH
  )
} else {
  multplt
}
```


```{r}
multplt.overlay <- plot_grid(plotlist = list(pltSexdisc, plt.overlay.age, pltfam,
                          pltHBP, pltSmoke,
                          pltMulti, plt.loc.comb, plt.overlay.size,
                          pltRupt),
          ncol = 3)

if (SAVEPLOTS) {
  ggsave(
    plot = multplt.overlay,
    filename = "vars_overview_multiplt_overlay.png",
    path = PLOTPATH,
    dpi = 300, width = PLOTWIDTH, height = PLOTHEIGHT*1.2
  )
} else {
  multplt.overlay
}
```

```{r}
multplt.overlay.small <- cowplot::plot_grid(plotlist = list(plt.loc.comb.large,
                                                   plt.overlay.age.large, 
                                                   plt.overlay.size.mm.large),
          ncol = 3)


if (SAVEPLOTS) {
  # ggsave(
  #   plot = multplt.overlay.small,
  #   filename = "vars_overview_multiplt_overlay_small.png",
  #   path = PLOTPATH,
  #   dpi = 300, width = PLOTWIDTH*2.6, height = PLOTHEIGHT*1.2
  # )
  ggsave(
    plot = multplt.overlay.small,
    filename = "vars_overview_multiplt_overlay_small.pdf",
    path = PLOTPATH,
    dpi = 300, width = PLOTWIDTH*2, height = PLOTHEIGHT*1.2
  )
} else {
  multplt.overlay.small
}
```


# No. of records per category

```{r}
dfdbn.renamed <- dfdbn %>%
  rename(c("Sex" = "Gender",
           # "Sex = Female" = "Gender.Female",
           # "Sex = Male" = "Gender.Male",
           "Fam. History" = "Positive.famillial.history",
           # "Fam. History = No" = "Positive.famillial.history.No",
           # "Fam. History = Yes" = "Positive.famillial.history.Yes",
           "Age" = "AgeDiag.group",           
           # "Age = F" = "AgeDiag.group.F",
           # "Age = G" = "AgeDiag.group.G",
           # "Age = D" = "AgeDiag.group.D",
           # "Age = E" = "AgeDiag.group.E",
           # "Age = C" = "AgeDiag.group.C",
           # "Age = B" = "AgeDiag.group.B",
           # "Age = A" = "AgeDiag.group.A",
           "Hypertension" = "Hypertension",
           # "Hypertension = Never" = "Hypertension.Never",
           # "Hypertension = AnyType" = "Hypertension.AnyType",
           "Smoking" = "Smoking_Current_Former_No",
           # "Smoking = Current" = "Smoking_Current_Former_No.Current",
           # "Smoking = Former" = "Smoking_Current_Former_No.Former",
           # "Smoking = No" = "Smoking_Current_Former_No.No",
           "Location" = "location.grouped",
           # "Location = High risk" = "location.grouped.High",
           # "Location = Medium risk" = "location.grouped.Medium",
           # "Location = Low risk" = "location.grouped.Low",
           "IA size" = "IAsize.groups.merged",
           # "IA size = A" = "IAsize.groups.merged.A",
           # "IA size = B" = "IAsize.groups.merged.B",
           # "IA size = C" = "IAsize.groups.merged.C",
           "Multiple IAs" = "Multiple.IAs",
           # "Multiple IAs = Yes" = "Multiple.IAs.Yes",
           # "Multiple IAs = No" = "Multiple.IAs.No",
           "Ruptured IA" = "Ruptured_IA"
           # "Ruptured IA = Yes" = "Ruptured_IA.Yes",
           # "Ruptured IA = No" = "Ruptured_IA.No"
           )) %>%
    select(-c(Age, `IA size`))

variables <- c()
varlevels <- c()
varlevn <- c()
for(c in names(dfdbn.renamed)){
  varlevs <- levels(dfdbn.renamed[[c]])
  variables <- c(variables, rep(c, length(varlevs)))
  varlevels <- c(varlevels, varlevs)
  varlevn <- c(varlevn, as.numeric(summary(dfdbn.renamed[[c]])))
  # varlevnrel <- c(varlevnrel, )
}

text_tbl <- data.frame(variables, varlevels, varlevn) %>%
  group_by(variables, varlevels) %>%
  summarise(n=varlevn, .groups = "drop_last") %>%
  mutate(varlevnrel = scales::percent(n/sum(n), accuracy = 0.1)) %>%
  # mutate(varlevnrel = round(n/sum(n), 2)) %>%
  ungroup()

text_tbl$variables_cleaned <- " "
for(r in 2:nrow(text_tbl)){
  current <- text_tbl[r,1]
  upper <- text_tbl[r-1,1]
  
  if(r==2){
    text_tbl$variables_cleaned[r-1] <- current
  } else if(current == upper){
    text_tbl$variables_cleaned[r] <- " "
  } else {
    text_tbl$variables_cleaned[r] <- current
  }
}
text_tbl$variables_cleaned <- unlist(text_tbl$variables_cleaned)
text_tbl

text_tbl %>%
  select(c(variables_cleaned, varlevels, n, varlevnrel)) %>%
  rename("Factor" = "variables_cleaned",
         "Level" = "varlevels",
         "Number of records" = "n",
         "Rel. no. of records" = "varlevnrel") %>%
  
  kbl(format = "latex", booktabs = T) %>%
  # kable_classic(full_width = F) %>%
  kable_styling(latex_options=c("striped", "hold_position", "scale_down"),
                # stripe_index = c(1,3,5,7,10,12)) %>%
                stripe_index = c(1,2,5,6,7,10,11)) %>%
  column_spec(3) %>%
  # kableExtra::landscape() %>%
  cat(., file = paste0(PLOTPATH, "/vars_overview_table.tex"))
```




# Stacked

All vars, stacked except for size and age


```{r}
dfdbn %>%
  select(Ruptured_IA) %>%
  gather(cols, value) %>%

  ggplot() +
  aes(x= cols, fill = value)  +
  geom_bar()
```


```{r}
legend_ord <- c()
for (c in colnames(select(dfdbn, -c(AgeDiag.group, IAsize.groups.merged)))){
  legend_ord <- c(legend_ord, levels(dfdbn[[c]]))
}
legend_ord <-unique(legend_ord)

dfdbn %>%
  select(-c(AgeDiag.group, IAsize.groups.merged)) %>%
  gather(cols, value) %>%

  ggplot() +
  aes(x= cols, fill = value)  +
  geom_bar() +
  # scale_fill_colorblind() +
  # scale_fill_tableau()
  scale_fill_stata(breaks=legend_ord)+
  coord_flip()
```

