---
title: "Correlation Analysis"
author: "Matteo Delucchi"
output:
  rmarkdown::html_document:
    toc: yes
    toc_float:
      collapsed: true
      smooth_scroll: false
    toc_depth: 3
  rmarkdown::html_vignette: default
vignette: >
  %\VignetteIndexEntry{correlation_analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# Clear working environment
rm(list=ls())

# Load libraries
library(bnaiaR)
library(bnlearn)
library(tidyr)
library(dplyr)
library(ggplot2)

# Save plots as files? 
# Warning: Bad layout with knitr. Works well if chunks are run without rendering.
SAVEPLOTS <- FALSE
PLOTPATH <- Sys.getenv("PLOTPATH")
PLOTFORMAT <- "png" # "svg" or "png"
```

# Load Data

```{r}
dataraw <- exp11_dat$abndata
```

```{r}
dataraw %>%
  mutate(id = row_number()) %>%
  tidyr::pivot_longer(cols = Gender, names_to = "Gender", values_to = "count") %>%
  pivot_wider(names_from = c("Gender", "count"), values_from = "count", values_fn = function(x){
    if(as.numeric(x)){
      1
      } else if(is.na(x)){
        0}
    }
  )
  # reshape2::dcast(Gender ~ Gender, drop = F, fill = 0) 
```

# One-hot encode data

```{r}
split2 <- function(x= dataraw$Gender){
  vals <- unique(x)
  df <- as.data.frame(matrix(ncol = length(vals), dimnames = list(NULL, vals)))
  
  v <- 1
  while (v <= length(vals)) {
    for (i in 1:length(x)) {
      if (x[[i]] == vals[v]){
        df[i,v] <- 1 
      } else {
        df[i,v] <- 0
      }
    }
    v <- v+1
  }
  
  return(df)
}
split2()
```


```{r}
dfonehot <- lapply(dataraw, split2) %>%
  do.call("cbind",.)
str(dfonehot)
```


```{r}
dfonehot <- dfonehot %>%
  rename(c("Sex = Female" = "Gender.Female",
           "Sex = Male" = "Gender.Male",
           "Fam. History = No" = "Positive.famillial.history.No",
           "Fam. History = Yes" = "Positive.famillial.history.Yes",
           "Age = F" = "AgeDiag.group.F",
           "Age = G" = "AgeDiag.group.G",
           "Age = D" = "AgeDiag.group.D",
           "Age = E" = "AgeDiag.group.E",
           "Age = C" = "AgeDiag.group.C",
           "Age = B" = "AgeDiag.group.B",
           "Age = A" = "AgeDiag.group.A",
           "Hypertension = Never" = "Hypertension.Never",
           "Hypertension = AnyType" = "Hypertension.AnyType",
           "Smoking = Current" = "Smoking_Current_Former_No.Current",
           "Smoking = Former" = "Smoking_Current_Former_No.Former",
           "Smoking = No" = "Smoking_Current_Former_No.No",
           "Location = High risk" = "location.grouped.High",
           "Location = Medium risk" = "location.grouped.Medium",
           "Location = Low risk" = "location.grouped.Low",
           "IA size = A" = "IAsize.groups.merged.A",
           "IA size = B" = "IAsize.groups.merged.B",
           "IA size = C" = "IAsize.groups.merged.C",
           "Multiple IAs = Yes" = "Multiple.IAs.Yes",
           "Multiple IAs = No" = "Multiple.IAs.No",
           "Ruptured IA = Yes" = "Ruptured_IA.Yes",
           "Ruptured IA = No" = "Ruptured_IA.No")) %>% 
  select(c("Sex = Female", 
           "Sex = Male",
           "Fam. History = Yes",
           "Fam. History = No",
           "Age = A",
           "Age = B",
           "Age = C",
           "Age = D",
           "Age = E",
           "Age = F",
           "Age = G",
           "Hypertension = AnyType",
           "Hypertension = Never",
           "Smoking = Current",
           "Smoking = Former",
           "Smoking = No",
           "Location = High risk",
           "Location = Medium risk",
           "Location = Low risk",
           "IA size = A",
           "IA size = B",
           "IA size = C",
           "Multiple IAs = Yes",
           "Multiple IAs = No",
           "Ruptured IA = Yes",
           "Ruptured IA = No"))
```

# Chi-square Test

```{r}
x <- chisq.test(dataraw$Gender, dataraw$Positive.famillial.history)
corrplot::corrplot(x$residuals, is.corr = F)
x$residuals

x$p.value
x
```

H0: vars sind unabhängig.

```{r}
x <- chisq.test(dataraw$Ruptured_IA, dataraw$Smoking_Current_Former_No)
corrplot::corrplot(x$residuals, is.corr = F)
x$residuals

x$p.value
x
```



```{r}
# chisq.overall <- function(x=dataraw){
#   cordf <- matrix(nrow = 26)
#   # for each variable
#   for(v in 1:length(colnames(x))){
#     w <- 1
#     while (w <= length(colnames(x))) {
#       chi <- chisq.test(x[[v]], x[[w]]) 
#       browser()
#       cordf[c(v:w),] <- cbind(cordf, chi$residuals)
#       w <- w+1
#     }
#   }
#   # correlation to all others
#   return(cordf)
# }
# chisq.overall()
```

# Pearson's Correlation Matrix

```{r}
# mat : is a matrix of data
# ... : further arguments to pass to the native R cor.test function
cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}

dfcor <- cor(dfonehot, method = "pearson")

# matrix of the p-value of the correlation
p.mat <- cor.mtest(dfonehot)
head(p.mat[, 1:5])

# Specialized the insignificant value according to the significant level
corrplot::corrplot(dfcor, type="upper", order="original", p.mat = p.mat, sig.level = 0.01)
```


```{r}
# Leave blank on no significant coefficient
plt <- corrplot::corrplot(dfcor, type="upper", 
                   
                   method = "color",
                   # method = "shade",
                   # method = "ellipse",
                   
                   # addCoef.col = "black", # Add coefficient of correlation
                   
                   tl.col="black", tl.srt=45, tl.cex = 0.6, #Text label color, rotation, size
                   
                   # Combine with significance
                   p.mat = p.mat,
                   
                   # sig.level = 0.01, insig = "blank", 
                   insig = 'label_sig', sig.level = c(0.001, 0.01, 0.05), pch.cex = 0.9, pch.col = 'grey20',
                   
                   # order = "hclust", addrect = 1, rect.col = "blue", rect.lwd = 4,
                   order="original",
                   
                   # hide correlation coefficient on the principal diagonal
                   diag=T
                   )

if (SAVEPLOTS){
  PLOTNAME <- "corrplot"
  dev.print(png, filename =paste0(PLOTPATH, "/", PLOTNAME, ".png"),
            res = 600, width = 6000)
  dev.off()
  } 
```

