---
title: "Playground abn with glmm"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Playground abn with glmm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bnaiaR)
# renv::install("url::https://git.math.uzh.ch/mdeluc/devel-abn/-/archive/v3.0.0.9000/devel-abn-v3.0.0.9000.tar.gz")
# renv::install("gitlab@git.math.uzh.ch::mdeluc/devel-abn/-/releases/v3.0.0.9000")
# renv::install("gitlab@git.math.uzh.ch::mdeluc/devel-abn/abn")
renv::install("../../../rrr/devel-abn/abn_3.0.0.9000.tar.gz")
library(abn)
# renv::install("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/stable"))
```

```{r}
SEED <- 123456789
```


# abn example 3
```{r}
mydat <- ex3.dag.data ## this data comes with abn see ?ex3.dag.data
str(mydat)
mydists <- list(b1="binomial", b2="binomial", b3="binomial",
            b4="binomial", b5="binomial", b6="binomial", b7="binomial",
            b8="binomial", b9="binomial", b10="binomial",b11="binomial",
            b12="binomial", b13="binomial" )
max.par <- 2

## in this example INLA is used as default since these are glmm nodes
## when running this at node-parent combination 71 the default accuracy check on the
## INLA modes is exceeded (default is a max. of 10 percent difference from
## modes estimated using internal code) and a message is given that internal code
## will be used in place of INLA's results.

mycache <- buildScoreCache(data.df=mydat, data.dists=mydists, group.var="group",
                        cor.vars=c("b1","b2","b3","b4","b5","b6","b7",
                                   "b8","b9","b10","b11","b12","b13"),
                        max.parents=max.par, which.nodes=c(1))
str(mycache)

table(mycache$used.INLA, useNA = "always")
```


# Data preparation

```{r}
data("exp4_dat")
df5 <- exp4_dat$abndata
str(df5)
```


```{r}
df51 <- df5
str(df51)
(banned51 <- exp4_dat$banned)
(retain51 <- exp4_dat$retain)
(dist51 <- exp4_dat$dist)
```

# ABN with glmm

```{r}
mycache <- buildScoreCache(method="mle",
                           data.df=df51,
                           data.dists=dist51[-10], # all except study_source
                           group.var="study_source",
                           dag.banned = banned51[-10, -10], # all except study_source
                           dag.retained = retain51[-10, -10], # all except study_source
                           max.parents=9,
                           control = build.control(catcov.mblogit = "diagonal",
                                                   seed = SEED),
                           verbose = F)
```

```{r}
mp.dag <- mostProbable(mycache)
```

```{r}
myres <- fitAbn(method="mle", 
                object = mp.dag, 
                group.var = "study_source",
                control = fit.control(catcov.mblogit = "diagonal",
                                      seed = SEED))
```

```{r}
plotAbn(myres)
```

```{r}
dfsim <- simulateAbn(object = myres,
                     verbose = TRUE,
                     seed = SEED,
                     run.simulation = TRUE,
                     n.chains = 100,
                     n.iter = 1e5,
                     n.thin = 1e3,
                     n.adapt = 1e2)
# dfsim <- simulateAbn(object = myres, 
#                      verbose = TRUE, 
#                      seed = SEED, 
#                      run.simulation = TRUE)
```
IAsize and age have been centered around zero and therefore can have negative values.


No group.var from here on. Because we cannot simulate the grouping variable because we do not have meaningful predictors for it.

```{r}
dist51_sim <- dist51[-10]
# dist51_sim["IAlocation_group"] <- "binomial"
# tmp <- as.integer(dfsim$positive_famillial_history)
# tmp[1] <- 2
# dfsim$positive_famillial_history <- factor(tmp)
mycache_sim <- buildScoreCache(method="mle",
                           data.df=dfsim[, names(dist51[-10])], # reordered to match data.dists
                           data.dists=dist51_sim, # all except study_source
                           # group.var="study_source",
                           dag.banned = banned51[-10, -10], # all except study_source
                           dag.retained = retain51[-10, -10], # all except study_source
                           max.parents=9,
                           verbose = TRUE)
```

```{r}
mp.dag_sim <- mostProbable(mycache_sim)
```

```{r}
myres_sim <- fitAbn(method="mle", object = mp.dag_sim)
```

```{r}
plotAbn(myres_sim)
```

